CREATE DATABASE mydatabase;

USE mydatabase;

CREATE TABLE items (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    price DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
INSERT INTO items (name, price) VALUES
('Laptop', 29999.99),
('Smartphone', 15999.50),
('Headphones', 1999.00),
('Keyboard', 999.99),
('Mouse', 499.50);
